---
type: l3leaf
pod_name: POD1_LEAFS

l3leaf: # dynamic_key: node_type
  defaults:
    platform: vEOS-lab
    #platform: 7280R3
    loopback_ipv4_pool: 100.100.1.0/24
    loopback_ipv4_offset: 0
    vtep_loopback_ipv4_pool: 10.100.1.0/24
    uplink_switches: ['pod1-spine-1', 'pod1-spine-2']
    uplink_ipv4_pool: 10.255.255.0/24
    # mlag_peer_ipv4_pool: 10.255.1.0/31
    # mlag_peer_l3_ipv4_pool: 10.255.1.2/31
    mlag_peer_ipv4_pool: 10.255.1.0/24
    mlag_peer_l3_ipv4_pool: 10.255.2.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_route_servers: ['super-spine-1', 'super-spine-2']

  node_groups:
    - group: POD1_MLAG01
      bgp_as: 65000.101
      nodes:
        - name: pod1-leaf-1
          mgmt_ip: 192.168.0.11/24
        - name: pod1-leaf-2
          mgmt_ip: 192.168.0.12/24

    - group: POD1_MLAG02
      bgp_as: 65000.102
      nodes:
        - name: pod1-leaf-3
          mgmt_ip: 192.168.0.13/24
        - name: pod1-leaf-4
          mgmt_ip: 192.168.0.14/24
    - group: POD1_MLAG03
      bgp_as: 65000.103
      nodes:
        - name: pod1-leaf-5
          mgmt_ip: 192.168.0.15/24
        - name: pod1-leaf-6
          mgmt_ip: 192.168.0.16/24
    - group: POD1_MLAG04
      bgp_as: 65000.104
      nodes:
        - name: pod1-leaf-7
          mgmt_ip: 192.168.0.17/24
        - name: pod1-leaf-8
          mgmt_ip: 192.168.0.18/24
    - group: POD1_MLAG05
      bgp_as: 65000.105
      nodes:
        - name: pod1-leaf-9
          mgmt_ip: 192.168.0.19/24
        - name: pod1-leaf-10
          mgmt_ip: 192.168.0.20/24
    - group: POD1_MLAG06
      bgp_as: 65000.106
      nodes:
        - name: pod1-leaf-11
          mgmt_ip: 192.168.0.21/24
        - name: pod1-leaf-12
          mgmt_ip: 192.168.0.22/24
    - group: POD1_MLAG07
      bgp_as: 65000.107
      nodes:
        - name: pod1-leaf-13
          mgmt_ip: 192.168.0.23/24
        - name: pod1-leaf-14
          mgmt_ip: 192.168.0.24/24
    - group: POD1_MLAG08
      bgp_as: 65000.108
      nodes:
        - name: pod1-leaf-15
          mgmt_ip: 192.168.0.25/24
        - name: pod1-leaf-16
          mgmt_ip: 192.168.0.26/24

generate_cv_tags:
  topology_hints: true
  device_tags:
    - name: POD
      value: '1'

