---
type: l3leaf

l3leaf:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 100.100.2.0/24
    loopback_ipv4_offset: 0
    vtep_loopback_ipv4_pool: 10.100.2.0/24
    uplink_switches: ['pod2-spine-1', 'pod2-spine-2']
    uplink_ipv4_pool: 10.255.254.0/24
    # mlag_peer_ipv4_pool: 10.255.1.0/31
    # mlag_peer_l3_ipv4_pool: 10.255.1.2/31
    mlag_peer_ipv4_pool: 10.255.3.0/24
    mlag_peer_l3_ipv4_pool: 10.255.4.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_route_servers: ['super-spine-1', 'super-spine-2']

  node_groups:
    - group: POD2_MLAG01
      bgp_as: 65133
      nodes:
        - name: pod2-leaf-1
          id: 1
          mgmt_ip: 192.168.0.43/24
        - name: pod2-leaf-2
          id: 2
          mgmt_ip: 192.168.0.44/24

    - group: POD2_MLAG02
      bgp_as: 65134
      nodes:
        - name: pod2-leaf-3
          id: 3
          mgmt_ip: 192.168.0.45/24
        - name: pod2-leaf-4
          id: 4
          mgmt_ip: 192.168.0.46/24

    - group: POD2_MLAG03
      bgp_as: 65135
      nodes:
        - name: pod2-leaf-5
          id: 5
          mgmt_ip: 192.168.0.47/24
        - name: pod2-leaf-6
          id: 6
          mgmt_ip: 192.168.0.48/24

    - group: POD2_MLAG04
      bgp_as: 65136
      nodes:
        - name: pod2-leaf-7
          id: 7
          mgmt_ip: 192.168.0.49/24
        - name: pod2-leaf-8
          id: 8
          mgmt_ip: 192.168.0.50/24

    - group: POD2_MLAG05
      bgp_as: 65137
      nodes:
        - name: pod2-leaf-9
          id: 9
          mgmt_ip: 192.168.0.51/24
        - name: pod2-leaf-10
          id: 10
          mgmt_ip: 192.168.0.52/24

    - group: POD2_MLAG06
      bgp_as: 65138
      nodes:
        - name: pod2-leaf-11
          id: 11
          mgmt_ip: 192.168.0.53/24
        - name: pod2-leaf-12
          id: 12
          mgmt_ip: 192.168.0.54/24

    - group: POD2_MLAG07
      bgp_as: 65139
      nodes:
        - name: pod2-leaf-13
          id: 13
          mgmt_ip: 192.168.0.55/24
        - name: pod2-leaf-14
          id: 14
          mgmt_ip: 192.168.0.56/24

    - group: POD2_MLAG08
      bgp_as: 65140
      nodes:
        - name: pod2-leaf-15
          id: 15
          mgmt_ip: 192.168.0.57/24
        - name: pod2-leaf-16
          id: 16
          mgmt_ip: 192.168.0.58/24