---
type: l3leaf

l3leaf:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.100.0.128/26
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.100.1.128/26
    uplink_switches: ['pod3-spine-1', 'pod3-spine-2']
    uplink_ipv4_pool: 10.255.253.0/24
    mlag_peer_ipv4_pool: 10.255.1.128/27
    mlag_peer_l3_ipv4_pool: 10.255.1.160/27
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_route_servers: ['super-spine-1', 'super-spine-2']

  node_groups:
    - group: POD3_MLAG01
      bgp_as: 65105
      nodes:
        - name: pod3-leaf-1
          id: 9
          mgmt_ip: 192.168.0.19/24
        - name: pod3-leaf-2
          id: 10
          mgmt_ip: 192.168.0.20/24

    - group: POD3_MLAG02
      bgp_as: 65106
      nodes:
        - name: pod3-leaf-3
          id: 11
          mgmt_ip: 192.168.0.21/24
        - name: pod3-leaf-4
          id: 12
          mgmt_ip: 192.168.0.22/24
