---
type: l3leaf

l3leaf:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 100.100.3.0/24
    loopback_ipv4_offset: 0
    vtep_loopback_ipv4_pool: 10.100.3.0/24
    uplink_switches: ['pod3-spine-1', 'pod3-spine-2']
    uplink_ipv4_pool: 10.255.253.0/24
    # mlag_peer_ipv4_pool: 10.255.1.0/31
    # mlag_peer_l3_ipv4_pool: 10.255.1.2/31
    mlag_peer_ipv4_pool: 10.255.5.0/24
    mlag_peer_l3_ipv4_pool: 10.255.6.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_route_servers: ['super-spine-1', 'super-spine-2']

  node_groups:
    - group: POD3_MLAG01
      bgp_as: 65000.105
      nodes:
        - name: pod3-leaf-1
          id: 1
          mgmt_ip: 192.168.0.75/24
        - name: pod3-leaf-2
          id: 2
          mgmt_ip: 192.168.0.76/24

    - group: POD3_MLAG02
      bgp_as: 65000.106
      nodes:
        - name: pod3-leaf-3
          id: 3
          mgmt_ip: 192.168.0.77/24
        - name: pod3-leaf-4
          id: 4
          mgmt_ip: 192.168.0.78/24
