---
type: l3leaf

l3leaf:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.100.0.192/26
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.100.1.192/26
    uplink_switches: ['pod4-spine-1', 'pod4-spine-2']
    uplink_ipv4_pool: 10.255.252.0/24
    mlag_peer_ipv4_pool: 10.255.1.192/27
    mlag_peer_l3_ipv4_pool: 10.255.1.224/27
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    evpn_route_servers: ['super-spine-1', 'super-spine-2']

  node_groups:
    - group: POD4_MLAG01
      bgp_as: 65107
      nodes:
        - name: pod4-leaf-1
          id: 13
          mgmt_ip: 192.168.0.23/24
        - name: pod4-leaf-2
          id: 14
          mgmt_ip: 192.168.0.24/24

    - group: POD4_MLAG02
      bgp_as: 65108
      nodes:
        - name: pod4-leaf-3
          id: 15
          mgmt_ip: 192.168.0.25/24
        - name: pod4-leaf-4
          id: 16
          mgmt_ip: 192.168.0.26/24
