---
    type: super-spine
    
    super_spine: # dynamic_key: node_type
      defaults:
        platform: vEOS-lab
        bgp_as: 65000
        loopback_ipv4_pool: 100.100.6.0/26
        loopback_ipv4_offset: 0
    
      nodes:
        - name: super-spine-1
          mgmt_ip: 192.168.0.1/24
        - name: super-spine-2
          mgmt_ip: 192.168.0.2/24